### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by NaoY-2501** [NaoY-2501/simple_spotify#5]
- [ ] : TestCode

- [ ] : Implement Player API

- [ ] : Implement Playlist API

- [ ] : Document on GitHub Wiki

- [ ] : Refactoring

- [ ] : Sample code
